providers:
  - python

setup:
  - python3 -m venv venv
  - . venv/bin/activate
  - pip install --upgrade pip
  - pip install wheel setuptools
  - pip install .
  - pip list

start:
  cmd: python3 -m scraperai.cli.app
