providers:
  - python

setup:
  - python3 -m venv /opt/venv
  - . /opt/venv/bin/activate
  - pip install --upgrade pip
  - pip install wheel setuptools
  - pip install -r requirements.txt
  - pip install .
  - pip list
  - which scraperai || echo "scraperai command not found"

start:
  cmd: python3 -m scraperai.cli.app
