name: Publish to pypi

on:
  release:
    types:
      - published

permissions:
  id-token: write
  contents: read

jobs:
  publish_to_pypi:
    name: publish to pypi on new release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup environment, python and requirements
        run: |
          pip install setuptools wheel twine
          python setup.py install
      - name: Build and upload
        run: |
          python setup.py sdist bdist_wheel --dist-dir ddist/
          python -m twine upload ddist/* -u __token__ -p ${{ secrets.TWINE_PASSWORD }}